name: Deno Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Module
        uses: actions/checkout@v3
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # use the latest deno

      - name: Run test
        # ↓ if you use env
        # env:
        #   YOUR_SECRET_KEY: ${{ secrets.YOUR_SECRET_KEY }} 
        run: deno task test

        # ↓ if you use Codecov
        # run: deno task test:cov

      # - name: Codecov
      #   uses: codecov/codecov-action@v1.5.2
      #   with:
      #     file: ./coverage.lcov
      #     fail_ci_if_error: true
  